### ISSUE TITLE
Issue on page /Lecture1.html

### ISSUE THREAD

**Issue by ahm531** [aronwalsh/MLforMaterials#1]
In the section 1.2.2. Plotting with Matplotlib, running the following cell produces an error. 
```
# Imports
import matplotlib.pyplot as plt  # Plotting
import numpy as np  # Numerical operations
%matplotlib inline  # Inline plotting for Jupyter notebooks

x = np.arange(0, 10, 0.001) # x = 0 to 10 in steps of 0.001
y = np.sin(x*x) # define your function
plt.figure(figsize=(5, 3)) # create a new figure (5x3 inches)
plt.plot(,y) # plot x against y
```
Error message: 
**Cell In[4], line 9
    plt.plot(,y) # plot x against y
             ^
SyntaxError: invalid syntax**

Fixing the plt.plot function argument to plt.plot(x,y), running the cell still produces the following error. 
Error message:
**UsageError: unrecognized arguments: # Inline plotting for Jupyter notebooks**

Removing the comment # Inline plotting for Jupyter notebooks fixes the problem.

**Comment by aronwalsh** [comment]
Thank you Ahmed. 

Actually, the notebooks have several deliberate mistakes to slow my students down. Otherwise, it is too easy to keep running cells without thinking.  The use of `%matplotlib inline` may depend on the setup.
